### ISSUE TITLE
MEL or not MEL spectrograms when dealing with high-frequences - tips ?

### ISSUE THREAD

**Issue by gg4u** [nilomr/pykanto#22]
I have a question about choosing if MEL or not MEL, and some tips for choosing parameters 

- Does pykanto let choose if using MEL spectrograms or not ?

I read your work is inspired and built upon the work of Tim Sainsburg; in Tim's repo, I see the option for creating spectrogram by using MEL or not:
[](https://github.com/timsainb/avgn_paper/blob/63e25ca535a230f96b7fb1017728ead6ee0bf36b/avgn/signalprocessing/create_spectrogram_dataset.py)

but could not see in:
[](https://nilomr.github.io/pykanto/_build/html/contents/segmenting-vocalisations.html
)

- Some tips for choosing parameters

For my understanding, MEL spectrograms transform distances between frequencies into _human_ audible spectrum, by using a log transformation.

That means, the delta between higher frequencies will be much smaller than the delta between lower frequencies, to address perception of humans who can discriminate better between lower frequency sounds than higher frequency ones.

But what if I am working with species who "speak" with high frequencies or ultra-sounds : 

- Which kind of advantages or disadvantages may I expect, in using MEL in this cases ?
 
I wonder : 

- can MEL still effectively lead to a " meaningful training" in ML approaches, or UMAP clustering, if the delta between higher frequencies is squeezed ? some advices in setting params for MELs when dealing with high frequencies ?

- Or, better to consider not using MEL, but the original spectrogram or other techniques for preprocessing data (likely in the steps of segmentation, I would expect)?

**Comment by nilomr** [comment]
- 'pykanto' uses mel spectrograms, which have been shown to work well with birds and other mammals (though I suspect that part of the reason why the scale is so widespread has to do with inertia and not so much an abundance of good evidence). 
- You're absolutely right that this might not be the best choice in all cases. Having a quick look at the bat literature it does seem that people use the mel scale to represent their vocalisations, but I don't know if this is a good practice. 
Ideally, your representation of a signal would follow a good perceptual model for the species in question if you're interested in behavioural Qs.
- I'd like to support 'linear' spectrograms but haven't the time to implement this - PRs always welcome!
