### ISSUE TITLE
Segmenting Files with customed data segmentations - Using SegmentAnnotation Class Or must I need to feed XML files? 

### ISSUE THREAD

**Issue by gg4u** [nilomr/pykanto#24]
Let's consider the use case when there is a database that comes already with segments descriptions, but lacking labels.

Is it possible to feed a `SegmentAnnotation` Class, or dictionary, into the `segment_files_parallel()` function ?
[](https://nilomr.github.io/pykanto/_build/html/_autosummary)[/pykanto.utils.types.html#pykanto.utils.types.SegmentAnnotation](url)

https://nilomr.github.io/pykanto/_build/html/contents/segmenting-files.html

Looking at your tutorial, it seems one **must have** a copy of XML files, that are used to prepare the files to segment:

`files_to_segment = get_wavs_w_annotation(wav_filepaths, xml_filepaths)`

and then feed the list of tuples (wave_paths, xml_paths) in:
```
segment_files_parallel(
    files_to_segment,
    ...
)
```

Instead, I would like to pass tuples of (wave_files, info_about_segments) where info_about_segments could be a dictionary, or SegmentAnnotation object.

As an example, consider this workflow:

1. I may load a dataset in pandas: 
<img width="978" alt="Screenshot 2023-02-28 at 2 52 31 PM" src="https://user-images.githubusercontent.com/284214/221875890-ed6173d1-2b9a-433b-8998-b77f6a76a0b0.png">

2. From there, I already have info about the segments starts/ ends, but not the labels (which are the things I want to classify by clustering)

3. I would like to avoid to create temporary xml files on disks, and instead extract directly a dictionary, or a class, for each row on the fly, and then pass it to segment_files_parallel( ).

Is it possible?

**Comment by nilomr** [comment]
Hi,

That is how things work, yes. You can either 
1. Prepare your dataset so that it can be ingested using `pykanto` (i.e., have a metadata file per audio file), or 
2. Modify the relevant functions to do what you want, e.g. like you mention you could pass a `SegmentAnnotation` object or similar to https://github.com/nilomr/pykanto/blob/2f92a9406f3618d8f6c8ca5acc6bb3b0326704fb/pykanto/signal/segment.py#L261
