### ISSUE TITLE
Issue Installing pykanto with Jupyter Notebook on macOS - Dependency Conflicts with attrs and jsonschema

### ISSUE THREAD

**Issue by advaymishra2003** [nilomr/pykanto#40]
@nilomr

I'm trying to set up the pykanto library in a Conda environment on macOS for bioacoustic data analysis, but I've encountered persistent issues with dependencies, specifically involving attrs, jsonschema, and jupyter_events. I’d appreciate any help troubleshooting or resolving these conflicts.

System Details:
OS: macOS (ARM architecture)
Python Version: 3.9 (installed via Anaconda)
Conda Environment: Created specifically for pykanto
Problem Description:
I initially installed pykanto using Conda and pip, but I encountered errors when trying to open Jupyter Notebook in the environment. The main issue seems to be conflicting dependencies among attrs, jsonschema, and jupyter_events, which are required by jupyter and pykanto.

Steps I Took:
Created a new Conda environment with Python 3.9 and installed Jupyter Notebook.

Followed the macOS-specific installation guide for pykanto:

Installed dependencies like libsndfile and grpcio.
Installed pykanto via pip.
When trying to launch Jupyter Notebook in this environment, I encountered the following error:

ModuleNotFoundError: No module named 'attrs'
I attempted to resolve this by upgrading attrs to version 24.2.0, which leads to further issues:

ERROR: "pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts. audio-metadata 0.11.1 requires attrs<19.4,>=18.2, but you have attrs 24.2.0 which is incompatible."
Specific Error Message:
When attempting to run Jupyter Notebook, I get this traceback:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/pykanto_env/bin/jupyter-notebook", line 7, in <module>
    from notebook.app import main
  File "/opt/anaconda3/envs/pykanto_env/lib/python3.9/site-packages/notebook/app.py", line 17, in <module>
    from jupyter_server.serverapp import flags
  File "/opt/anaconda3/envs/pykanto_env/lib/python3.9/site-packages/jupyter_server/serverapp.py", line 39, in <module>
    from jupyter_events.logger import EventLogger
  File "/opt/anaconda3/envs/pykanto_env/lib/python3.9/site-packages/jupyter_events/__init__.py", line 3, in <module>
    from .logger import EVENTS_METADATA_VERSION, EventLogger
  File "/opt/anaconda3/envs/pykanto_env/lib/python3.9/site-packages/jupyter_events/logger.py", line 19, in <module>
    from .schema import SchemaType
  File "/opt/anaconda3/envs/pykanto_env/lib/python3.9/site-packages/jupyter_events/schema.py", line 18, in <module>
    from .validators import draft7_format_checker, validate_schema
  File "/opt/anaconda3/envs/pykanto_env/lib/python3.9/site-packages/jupyter_events/validators.py", line 44, in <module>
    JUPYTER_EVENTS_SCHEMA_VALIDATOR = Draft7Validator(
TypeError: __init__() got an unexpected keyword argument 'registry'

pykanto requires specific versions of attrs and jsonschema that conflict with the requirements for jupyter_events, which is essential for Jupyter Notebook.
Dependencies like audio-metadata and tbm-utils in pykanto cause compatibility issues when attempting to use updated versions of attrs and jsonschema.
Questions:
Has anyone successfully installed pykanto with Jupyter on macOS without these dependency conflicts?
Are there compatible versions of attrs, jsonschema, and jupyter_events that work together with pykanto?
Should I separate pykanto and Jupyter into different environments?

**Comment by nilomr** [comment]
Hi @advaymishra2003!

Thanks for pointing this out. Since Jupyter isn’t a dependency of `pykanto` and I don’t use it, this issue hadn’t come up before. However, as you’ve noted, some dependency conflicts arise due to newer versions of libraries Jupyter relies on.

I've added a patch with optional dependencies for Jupyter that should resolve these conflicts. You can try installing `pykanto` with Jupyter support as follows:

```bash
conda create -n <env_name> python=3.9 -y
conda activate <env_name>
pip install pykanto'[jupyter]'
```

Let me know if this helps or if you encounter other issues!

**Comment by advaymishra2003** [comment]
@nilomr 

Thank you so much for the advice and the patch! It worked quite well on jupyter notebook.

**Comment by nilomr** [comment]
Hi Advay,

Could you please provide a reproducible example, including traceback? In the meantime, the docs might help: https://nilomr.github.io/pykanto/_build/html/contents/project-setup.html

**Comment by advaymishra2003** [comment]
Hi @nilomr ,

Thank you for getting back to me so quickly! Here's a reproducible example of the issue I encountered, along with the traceback.

import pykanto
from pykanto.dataset import KantoData
from pykanto.parameters import Parameters

# Step 1: Define paths for data and output
data_dir = "wav_files"   # Directory containing audio (.wav) and JSON files
output_dir = "wav_files/output"  # Directory for output

# Step 2: Initialize Parameters
params = Parameters(
    data_dir=data_dir,
    output_dir=output_dir,
    lowcut=0,
    highcut=7000,
    window_size=0.03,
    overlap=0.5,
    threshold=0.1,
    song_level=False
)

# Step 3: Initialize the KantoData object
dataset = KantoData(DIRS=params, parameters=params)  # Using params for DIRS


Traceback
Here’s the traceback from the execution:
AttributeError: 'Parameters' object has no attribute 'DATASET_ID'
Traceback (most recent call last):
  File "/opt/anaconda3/envs/pykanto_env_jupyter/lib/python3.9/site-packages/pykanto/dataset.py", line 110, in __init__
    self.DATASET_ID = DIRS.DATASET_ID
AttributeError: 'Parameters' object has no attribute 'DATASET_ID'

Since I couldn't import ProjDirs (as it wasn’t accessible), I tried a workaround by defining a custom CustomDirs class with the required attributes (DATASET_ID, DATA_DIR, OUTPUT_DIR) and passing it as the DIRS argument. Unfortunately, this also resulted in the same error.

Let me know if you need any additional details or files to reproduce the issue.

Thanks again for your support!

**Comment by nilomr** [comment]
Hi,

Please refer to the docs at https://nilomr.github.io/pykanto for examples of projects created using pykanto. As an example, here's one showing you how to [segment vocalisations into units](https://nilomr.github.io/pykanto/_build/html/contents/segmenting-vocalisations.html).

You can download these examples as Jupyter notebooks as well:
![image](https://github.com/user-attachments/assets/094f00b7-cddf-4e17-b962-4c78f449c4c4)

You can use your IDE or the pykanto docs to consult the documentation for each function. E.g., to see valid arguments and variable types that you can pass to the `KantoData` class, see [pykanto.dataset.KantoData](https://nilomr.github.io/pykanto/_build/html/_autosummary/pykanto.dataset.html?highlight=kantodata#pykanto.dataset.KantoData). Based on your example, it seems that you haven't created a `ProjDirs` object, which is the first argument that  `KantoData` expects. This is explained here: [set-up-project-directories](https://nilomr.github.io/pykanto/_build/html/contents/project-setup.html#set-up-project-directories).

Lastly, am not sure what you mean by this: "I couldn't import ProjDirs (as it wasn’t accessible)". Tests for pykanto are running OK; `from pykanto.utils.paths import ProjDirs` works on my side. 

Hope that helps!
Nilo

**Comment by nilomr** [comment]
Hi @advaymishra2003, I've moved your follow-up comment over to https://github.com/nilomr/pykanto/issues/41 as it represents a different issue - we can keep chatting there!
